services:
  - type: web
    name: darc-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.ccpighleiemxslknuvyh:fazin1980dxb@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: SECRET_KEY
        value: "a86cbc50849b00a86240caf7ab1c5be964fcdc485b78263c64b516cb93db2fa0"
